### ISSUE TITLE
Feature request: packaged volume on items

### ISSUE THREAD

**Issue by pedter** [evepraisal/go-evepraisal#10]
Some items change volume depending on their assembled/packaged state (the big three are ships, containers, and capital modules). Because the assembled volume is used by default, this can greatly skew the volume of a list of assets.

While I am unaware if the SDE also contains the packaged volume for each item, if it does, the two different volumes could be displayed in much the same way buy/sell price values are, with one above the other for each item type. Additionally, as with Total Sell and Total Buy Value listed at the bottom of the page, Total Assembled and Total Packaged Volume could be listed at the bottom of the page.

**Comment by sudorandom** [comment]
After doing a bit of research it looks like the packaged volumes are static per category of ship. Fuzzworks seems to have the packaged volumes here:
https://www.fuzzwork.co.uk/dump/latestyaml/

I will work on using this to display packaged volumes. I think packaged volumes makes sense for most items (that can be packaged) so I'll show that by default.

**Comment by sudorandom** [comment]
I released this just a bit ago.  Packaged volumes will be used for items that are able to be packaged.

**Comment by pedter** [comment]
Just testing things out; I'm not really sure what's going on here in this one - http://evepraisal.com/a/bxj8u

The station container is properly 10k m3, but the capital module is 4k (they're typically 1k packaged). Additionally, the battleship is reporting 15k (as if it's a battlecruiser, perhaps?) instead of 50k. Last up, the total volume calculated at the bottom of the page appears to be using assembled volume values instead of packaged values; this might actually be intended but is rather confusing in its current state.

**Comment by sudorandom** [comment]
Hrm, I'm not sure. 15,000 is what fuzzworks has for every battleship type. I feel like that data might is incorrect

**Comment by sudorandom** [comment]
@pedter I just pushed a change which basically hard-codes the packaged volumes for different ship types. Thanks for double-checking me!

**Comment by pedter** [comment]
Fantastic, thanks! I've just now had time to test them all out and there are still a couple of exceptions that slipped through, unfortunately. I'll create a new issue once I've tracked them all down.
