### ISSUE TITLE
Unknown Format

### ISSUE THREAD

**Issue by efferreiram** [evepraisal/go-evepraisal#104]
Appraisal with the format: evepraisal.com/a/mq0n1

Describe the format (where you got it, etc)

Example:
Transmitter	Refined Commodities - Tier 2	Planetary Commodities Hold	5605

If you have items inside an Epithal, and you view its contents through the Personal Assets window -> View Contents, this is the format you get. Items inside the Planetray Commodieties Hold have the issue that Evepraisal only detects quatity of 1 instead of the full amount.

**Comment by sudorandom** [comment]
This should be resolved now!
