### ISSUE TITLE
Unknown Format

### ISSUE THREAD

**Issue by TrueBlue22** [evepraisal/go-evepraisal#11]
Appraisal with the format: evepraisal.com/a/bxm54

Loot history from fleet. Doesn't seem to work. I deleted other players loot to value this players only but did not edit anything from the text as copied from fleet loot history.

I have also tried pasting the entire fleets loot history and also received an invalid result.

Thanks,
TrueBlue22

**Comment by sudorandom** [comment]
Can you do me a favor and send me some examples that I can test with? You can paste it as a comment here or email it to me at github@sudorandom.com

**Comment by sudorandom** [comment]
@TrueBlue22 your example should look like this now: http://evepraisal.com/a/by3cn

If you see any more problems feel free to share! Thanks!
