### ISSUE TITLE
Unknown Format

### ISSUE THREAD

**Issue by Armored22** [evepraisal/go-evepraisal#126]
Appraisal with the format: evepraisal.com/a/qb5a7

Adaptive Invulnerability Shield Hardener II
Anti-EM Shield Hardener II
Medium Inductive Compact Remote Capacitor Transmitter

Not working.

**Comment by greftek** [comment]
This impacts all the Shield hardener and shield resist amplification modules. This has likely to do with the renaming of said modules in the last monthly update.


https://www.eveonline.com/article/q8tteh/patch-notes-for-18-04-release
