### ISSUE TITLE
Invalid Input

### ISSUE THREAD

**Issue by geraldm74** [evepraisal/go-evepraisal#129]
When trying to get the price of a "Pithum C-Type Adaptive Invulnerability Shield Hardener", I'm getting an Invalid Input error message.

**Comment by Stealth385** [comment]
All items previously known as "Adaptive Invulnerability Field" have been renamed to "Adaptive Invulnerability Shield Hardener" - the site is probably still using old names for some reason.

**Comment by LordMrcS** [comment]
also invalid input for needlejack filaments
