### ISSUE TITLE
Using X doesnt work

### ISSUE THREAD

**Issue by ramseur** [evepraisal/go-evepraisal#13]
compressed bistot X 65 doenst work
compressed bistot x 65 does work.

Also when something fails you shouldnt clear the text box.  Just keep it there and allow the user to fix their mistake or Help fix the users mistake.  Makes for better UI.

**Comment by sudorandom** [comment]
Yeah, that's probably an unintentional bug. I'll look at it tonight (in 5-6 hours).

Thanks for the suggestion of not clearing the box. Expect it to be changed tonight.

**Comment by sudorandom** [comment]
@ramseur As promised, both changes have been made and pushed to the production site. Please try it for yourself! Thanks again for the feedback!
