### ISSUE TITLE
Rig name changes not applied to website.

### ISSUE THREAD

**Issue by TheEDFLegacy** [evepraisal/go-evepraisal#130]
When I attempted to add the following, it failed:

```
Medium Thermal Shield Reinforcer I	12	Rig Shield		Rigs	120 m3	1,708,261.32 ISK
Medium EM Shield Reinforcer I	12	Rig Shield		Rigs	120 m3	1,621,517.76 ISK
Medium Core Defense Field Extender I	12	Rig Shield		Rigs	120 m3	21,646,115.52 ISK
```

I believe it is because of the recent naming changes of some shield modules (check Kin/Therm, as well as Invulenerability Fields, among other things). Check the patch notes:

https://www.eveonline.com/article/qaxqcl/patch-notes-for-version-18-05

Here are the relevant changes:

Changed the name of module group Armor Reinforcer to Armor Plate and changed Blueprint group from Armor Reinforcer Blueprint to Armor Plate Blueprint.

Renamed all Shield and Armor Resistance Bonus Rigs and Their Blueprints
        Anti-EM Screen Reinforcer → EM Shield Reinforcer
        Anti-Explosive Screen Reinforcer → Explosive Shield Reinforcer
        Anti-Kinetic Screen Reinforcer → Kinetic Shield Reinforcer
        Anti-Thermal Screen Reinforcer → Thermal Shield Reinforcer
        Anti-EM Pump → EM Armor Reinforcer
        Anti-Explosive Pump → Explosive Armor Reinforcer
        Anti-Kinetic Pump → Kinetic Armor Reinforcer
        Anti-Thermal Pump → Thermal Armor Reinforcer

All Armor Hardeners and their blueprints were renamed as follows:
        FLAVORNAME Armor DAMAGETYPE Hardener → FLAVORNAME DAMAGETYPE Armor Hardener.

For example:
            Armor EM Hardener I → EM Armor Hardener I
            Corpus C-Type Armor Kinetic Hardener → Corpus C-Type Kinetic Armor Hardener

Experimental modules were renamed to Experimental Enduring modules

Prototype modules were renamed to Prototype Compact modules

Following modules have been converted:
        Upgraded EM Armor Hardener I → Experimental Enduring EM Armor Hardener I
        Upgraded Explosive Armor Hardener I → Experimental Enduring Explosive Armor Hardener I
        Upgraded Kinetic Armor Hardener I → Experimental Enduring Kinetic Armor Hardener I
        Upgraded Thermal Armor Hardener I → Experimental Enduring Thermal Armor Hardener I
        Limited EM Armor Hardener I → Prototype Compact EM Armor Hardener I
        Limited Explosive Armor Hardener I → Prototype Compact Explosive Armor Hardener I
        Limited Kinetic Armor Hardener I → Prototype Compact Kinetic Armor Hardener I
        Limited Thermal Armor Hardener I → Prototype Compact Thermal Armor Hardener I

All Adaptive Invulnerability Shield Hardeners have been renamed to Multispectrum Shield Hardeners.

The "Anti-" prefix has been removed from the names of all Shield Hardeners.

(There are other changes as well, including meta levels and m3)

![image](https://user-images.githubusercontent.com/7572037/83978553-5c1b9280-a8d6-11ea-97c4-5f64b77ce95e.png)

**Comment by sudorandom** [comment]
Try now. My regex for shield reinforcers was incomplete.
