### ISSUE TITLE
Unknown Format - Fleet history

### ISSUE THREAD

**Issue by fabienmazieres** [evepraisal/go-evepraisal#131]
Appraisal with the format: evepraisal.com/a/tnpv3

Describe the format (where you got it, etc)
 I took an export of the fleet history, attached the original
[Loot - 2020.06.25 08.55.45.txt](https://github.com/evepraisal/go-evepraisal/files/4830178/Loot.-.2020.06.25.08.55.45.txt)

**Comment by Asday** [comment]
Works fine for me.  Fixed in the meantime?
