### ISSUE TITLE
Unknown Format (item:qty)

### ISSUE THREAD

**Issue by UberMiguel** [evepraisal/go-evepraisal#133]
Appraisal with the format: evepraisal.com/a/uuh3y

Describe the format A really common, simple format that is a no-brainer to allow is:
item: qty
"Tritanium:  53333"

It's just easier to read and modify from scripts and long lists. Stupid easy to implement and makes sense without being as dumb/dangerous as item = qty, but probably not a problem for you to allow both, right?

**Comment by sudorandom** [comment]
This has been implemented!
