### ISSUE TITLE
Add capital module repackaged volumes

### ISSUE THREAD

**Issue by GunfighterJ** [evepraisal/go-evepraisal#14]
There are many capital modules with different repackaged volumes.

I believe these are all of them:

marketGroupId: `600, 771, 772, 773, 774, 775, 776, 777, 778, 910, 1052, 1063, 2240, 2241, 2242, 2243, 2244, 2245, 2246, 2247, 2250, 2251`
volume: `1000`

marketGroupId: `2249, 2267, 2268, 2269, 2270, 2276`
volume: `2000`

typeId: `41249, 41250, 41251, 41252, 41253, 41254, 41255, 41236, 41238, 41239, 41240, 41241, 41411, 24283, 41414, 41415`
volume: `1000`

typeId: `40715, 40716, 40717, 40718`
volume: `2000`

**Comment by sudorandom** [comment]
Where did you get all this information?

**Comment by GunfighterJ** [comment]
https://bitbucket.org/snippets/viktorielucilla/d4oyA/calculating-repackaged-volumes-for-eve

I went through all the lists and compared them in-game, they are accurate, though I did just find a missing one. `40714` should be added to the last list with all the other emergency hull energizers.

**Comment by sudorandom** [comment]
@GunfighterJ You're awesome. I just pushed up a change with all of these packaged volumes included. I wish CCP would provide an easy way to get all this information... It seems silly to not have in the static data export.

**Comment by GunfighterJ** [comment]
I'll bring the pitchforks :)
