### ISSUE TITLE
Incorrect packaged volume values

### ISSUE THREAD

**Issue by pedter** [evepraisal/go-evepraisal#17]
As best I can tell this is an exhaustive list of missing/outdated m3 values. Ship and capital module errors look like they were mostly caused by exceptions from the norm. Containers are still using the assembled volumes though this may actually be intentional.

Ships:
T3 cruisers are 5k m3 not 10k m3 - http://evepraisal.com/a/byf5b
Supercarriers are 1.3m m3 not 13m m3 - http://evepraisal.com/a/byf99
Titans are 10m m3 not 13m m3 - http://evepraisal.com/a/byf9d
Industrial ships are 20k m3 not 10k m3 - http://evepraisal.com/a/byfa5
The porpoise is 50k m3 not 500k m3 (orca to remain at 500k m3) - http://evepraisal.com/a/byfaa
Special edition industrial ships are 20k m3 not 10k m3 - http://evepraisal.com/a/byfb8

Containers:
Small audit/freight/secure/standard containers should be 10 m3 not 100/1k m3 - 
http://evepraisal.com/a/byfcv
Medium audit/secure/standard containers should be 33.0 m3 not 325 m3 - 
http://evepraisal.com/a/byfcc
Medium freight containers should be 50 m3 not 5k m3 - http://evepraisal.com/a/byfd5
Large audit/secure/standard containers should be 65 m3 not 650 m3 - http://evepraisal.com/a/byfce
Large freight containers should be 100 m3 not 1k m3 - http://evepraisal.com/a/byfd8
Huge secure containers should be 150 m3 not 1500 m3 - http://evepraisal.com/a/byfch
Huge freight containers should be 500 m3 not 50k m3 - http://evepraisal.com/a/byfdd
Giant secure containers should be 300 m3 not 3k m3 - http://evepraisal.com/a/byfck
Huge freight containers should be 1200 m3 not 120k m3 - http://evepraisal.com/a/byfdy
Enormous freight containers should be 2500 3m not 250k m3 - http://evepraisal.com/a/byfe2
Station containers should be 10k m3 not 2m m3 - http://evepraisal.com/a/byfec
Station vault containers should be 50k not 5m m3 - http://evepraisal.com/a/byfef
Station warehouse containers 100k m3 not 10m m3 - http://evepraisal.com/a/byfej

Capital modules:
Remote armor repairers should be 1k m3 not 4k m3 - http://evepraisal.com/a/byfi4
10000MN Y-S8 Compact Afterburner should be 1k m3 not 4k m3 - http://evepraisal.com/a/byfie
Sentient Fighter Support Unit should be 1k m3 not 2k m3 - http://evepraisal.com/a/byfjx
Siege modules should be 1k m3 not 4k m3 (except for t2 industrial cores, which are still 4k m3) - http://evepraisal.com/a/byfn4
Phenomena generators should be 8k m3 instead of 2k m3 (the rest of the DDs should remain at 2k m3) - http://evepraisal.com/a/byfo3

**Comment by sudorandom** [comment]
@pedter wow, so some of these items are able to be packaged but have the same volume as unpackaged?? Despite every other item similar to that one not behaving that way? That's crazy.

I pushed up a change that applies these changes

**Comment by pedter** [comment]
Excellent changes, thanks! Just a heads up, it looks like two things missed the cut - 

Transport ships should be 20k rather than 10k - http://evepraisal.com/a/bz85r
Phenomena generators are all 8k rather than 2k - http://evepraisal.com/a/bz82y
