### ISSUE TITLE
SDE Change breaks TypeID imports 

### ISSUE THREAD

**Issue by justindh** [evepraisal/go-evepraisal#176]
https://github.com/DeepwaterHooligans/go-evepraisal/commit/21a7ca4d1d67bc439ee3e2964782cfd65e848f77

my fix

If you are seeing lots of crashes, and on startup you see the error:

`fetcher.go:39: ERROR: failed to fetch static data from CCP: loading types: open db/types-`

CCP updated the checksum and file names, my above patch fixes it....some one might have a more elegant solution

**Comment by steven-cmy** [comment]
I confirm that this works. You should set up a pull request.

**Comment by sudorandom** [comment]
I merged in https://github.com/evepraisal/go-evepraisal/pull/177 so I'm closing this issue as well. Thanks for contributing!
