### ISSUE TITLE
quantity field thousand separator parsing issue (when not all columns are used)

### ISSUE THREAD

**Issue by Grauzunas** [evepraisal/go-evepraisal#19]
with eve columns: name/quantity/volume/est price

Fullerite-C72	8 898	17 796 m3	65 797 506,72 ISK

is 'invalid format' for eve prisal

removing gap in 8898 becomes readable format e.g.:
Fullerite-C72	8898	17 796 m3	65 797 506,72 ISK

with eve columns: name/quantity/category/volume/est price
Fullerite-C72	8 898	Celestial	17 796 m3	65 797 506,72 ISK
it is parsed but with 'The heuristic parser was used to parse this result. ' message

**Comment by sudorandom** [comment]
For documentation purposes, this it what is coming in that isn't working

```
Fullerite-C72\t8\u00a0898\t17\u00a0796 m3\t65\u00a0797\u00a0506,72 ISK
```
