### ISSUE TITLE
ISK/m3 calculated incorrectly

### ISSUE THREAD

**Issue by pedter** [evepraisal/go-evepraisal#2]
The ISK/m3 column is currently calculated by dividing total value by per-unit volume for each item type. This should be either per-unit value divided by per-unit volume or total value divided by total volume.

**Comment by sudorandom** [comment]
Whoops, I'll fix this ASAP @pedter

**Comment by sudorandom** [comment]
@pedter this should be fixed now

**Comment by pedter** [comment]
Indeed it has; a page refresh updated all values. Thanks!
