### ISSUE TITLE
Courier double wrap not showing up on appraisal

### ISSUE THREAD

**Issue by PureWhyte** [evepraisal/go-evepraisal#20]
http://evepraisal.com/a/bytg2 - Original scan
http://evepraisal.com/a/bytg2.raw

http://evepraisal.com/a/bysy5 - Original scan
http://evepraisal.com/a/bysy5.raw

Double wraps used to show up with a 0 value. Now just completely missing from paste

**Comment by sudorandom** [comment]
@PureWhyte Thanks for the report! This should be fixed now.
