### ISSUE TITLE
Add documentation for "POST /appraisal" endpoint

### ISSUE THREAD

**Issue by sudorandom** [evepraisal/go-evepraisal#23]

**Comment by NotARealTree** [comment]
Is there any specific part of the code we could look at until this is done?

**Comment by sudorandom** [comment]
This is the file: https://github.com/evepraisal/go-evepraisal/blob/master/web/handle_appraisal.go#L25

The gist is, appraisal contents get sent as the "raw_textarea" parameter or as a file via uploadappraisal.
The "market" is sent in as the "market" parameter. The valid options for that are "jita", "amarr", "dodixie", "hek" and "universe".

If successful, the new appraisal ID will be in an HTTP header called "X-Appraisal-ID".

**Comment by NotARealTree** [comment]
That's great, thanks for the explanation!

I look forward to using the JSON endpoint instead but this works in the meantime.

**Comment by sudorandom** [comment]
I added the JSON endpoint for creating new appraisals and have documented the API a bit better here: http://evepraisal.com/about/api

I'll close this issue but let me know how I can improve it.
