### ISSUE TITLE
With prices +/- 80%-200% its starting to be not usable :((

### ISSUE THREAD

**Issue by Aloerana** [evepraisal/go-evepraisal#25]
Lots of items have prices not covered by any trade hub for example:
http://evepraisal.com/a/c27vm

and 
https://eve-central.com/home/quicklook.html?typeid=43883

60mil and 360mil is big difference

**Comment by sudorandom** [comment]
Yeah, I plan to change this tonight.

What is happening is that low volume items like the one you linked are relying on CCP's prices. Those prices are sometimes incredibly inaccurate. I'm going to change this to trust any ongoing orders in the market over CCP's 'adjusted' prices.

I'll update here when I have pushed out the change. Thanks a bunch for the report!

**Comment by sudorandom** [comment]
@Aloerana This should look a lot better now: http://evepraisal.com/a/c2b0y

I'll mark this as closed but let me know if you notice anything like this.
