### ISSUE TITLE
Unknown Format

### ISSUE THREAD

**Issue by dmullaney** [evepraisal/go-evepraisal#28]
Appraisal with the format: evepraisal.com/a/ce49z

Copied from the Ship->View Contents window:

Compressed Concentrated Veldspar	Veldspar	Ore Hold	1288
Compressed Condensed Scordite	Scordite	Ore Hold	784
Compressed Dense Veldspar	Veldspar	Ore Hold	1625
Compressed Fiery Kernite	Kernite	Ore Hold	217
Compressed Golden Omber	Omber	Ore Hold	325
Compressed Hemorphite	Hemorphite	Ore Hold	64
Compressed Jaspet	Jaspet	Ore Hold	6
Compressed Kernite	Kernite	Ore Hold	225
Compressed Luminous Kernite	Kernite	Ore Hold	1099
Compressed Massive Scordite	Scordite	Ore Hold	1951
Compressed Omber	Omber	Ore Hold	627
Compressed Pristine Jaspet	Jaspet	Ore Hold	9
Compressed Pure Jaspet	Jaspet	Ore Hold	76
Compressed Pyroxeres	Pyroxeres	Ore Hold	266
Compressed Radiant Hemorphite	Hemorphite	Ore Hold	35
Compressed Scordite	Scordite	Ore Hold	368
Compressed Silvery Omber	Omber	Ore Hold	148
Compressed Solid Pyroxeres	Pyroxeres	Ore Hold	4615

**Comment by sudorandom** [comment]
Thanks for reporting this. This should be fixed now.
