### ISSUE TITLE
Navy Cap booster 3200

### ISSUE THREAD

**Issue by mirage113** [evepraisal/go-evepraisal#29]
i can't see the cap boosters in the eve praisal

**Comment by sudorandom** [comment]
With a quantity, cap boosters do work like this:
```
1 Navy Cap booster 3200
```

However, alone they don't:
```
Navy Cap booster 3200
```

This does seem like a bug

**Comment by sudorandom** [comment]
This should be fixed now: http://evepraisal.com/a/cgkee
