### ISSUE TITLE
Volume (m3) column ignores decimal values

### ISSUE THREAD

**Issue by pedter** [evepraisal/go-evepraisal#3]
As above; for particularly small items, the per-unit volume is rounded off. This appears to be during display only; ISK/m3 uses the appropriate decimal value for per-unit volume. This leads to things like isotopes (0.1m3) simply being displayed as 0m3.

**Comment by sudorandom** [comment]
This should be fixed on the live site. Sorry for the :CCP: math.

**Comment by pedter** [comment]
Looks like this is now working for items smaller than 1.00m3, but for others larger (like Mechanical Parts at 1.5m3), they're still being rounded up to 2m3 flat unfortunately.

**Comment by pedter** [comment]
Haven't been able to find anything else that this have been a problem for now. Thanks!
