### ISSUE TITLE
Ads - Auto Playing MAX volume can't mute

### ISSUE THREAD

**Issue by nmirro** [evepraisal/go-evepraisal#31]
WTF is up with the ads and not being able to mute them!  nothing like an ad blaring at loud volume while showing you it is "muted" but its actually a video behind the ad that you can't manipulate; so either I have to keep your page open and "mute the tab" (only available in Chrome) or I have to remember to rush to mute the tab each time I open a link to your site.

**Comment by sudorandom** [comment]
Wow, that is annoying. I'll see if I can disable those kinds of ads. Meanwhile, logged in users don't have any ads so there's a way to get rid of them altogether

**Comment by sudorandom** [comment]
I believe I disabled these kinds of ads. Let me know if they continue to play sound (or video).
