### ISSUE TITLE
[Patch] Fix makefile to correctly work with default $GOPATH

### ISSUE THREAD

**Issue by eveor** [evepraisal/go-evepraisal#34]
Go 1.8 added an default `$GOPATH`. If the developer is using the default without explicitly setting the environment variable the makefile will throw an error. I've enclosed a patch to fetch the inferred value of the variable from the go tool and updated one command that assumed `$GOPATH/bin` was in `$PATH` to correctly use a relative path from `$GOPATH`.

```
diff --git a/Makefile b/Makefile
index 71f91ca..589df41 100644
--- a/Makefile
+++ b/Makefile
@@ -12,6 +12,7 @@ endif

 GOOS?=$(shell go env GOOS)
 GOARCH?=$(shell go env GOARCH)
+GOPATH?=$(shell go env GOPATH)

 .PHONY: setup build install generate clean test test-reload run run-reload dist deploy

@@ -49,7 +50,7 @@ run: install
 	${GOPATH}/bin/evepraisal

 run-reload:
-	reflex -c reflex.conf
+	${GOPATH}/bin/reflex -c reflex.conf

 dist:
 	ENV=PROD GOOS=linux GOARCH=amd64 make build
```

**Comment by sudorandom** [comment]
I applied this patch to master. Thanks!
