### ISSUE TITLE
Overly large numbers cause interesting results

### ISSUE THREAD

**Issue by Hoeya** [evepraisal/go-evepraisal#35]
Problem: Looks like integer overflow. 

Issue: Overly large quantities of items that are placed within the pastebox are automatically assigned the lowest possible signed int64 value (-9,223,372,036,854,775,808), and then calculated out based on a negative item price. Leads to hilarious results and interesting calculations. 

Link: 
http://evepraisal.com/a/d04pt
https://i.imgur.com/OHEZsaP.png

Reproduction: Type in any item and add more than a 64-bit integer can handle. ( 1111111111111111111111111111111 Revelation is what I used.)

**Comment by sudorandom** [comment]
I'm not really sure this is worth fixing. I'm not moving to a variable-sized float or integer type for scenarios that are not realistic... I could switch everything to use an unsigned integer for counts, but I still feel like that's a lot of busy work for a bug that no one actually hits.

For those reasons, I'm going to go ahead and close this guy.
