### ISSUE TITLE
Add Rens to hubs list

### ISSUE THREAD

**Issue by nagledb** [evepraisal/go-evepraisal#37]
Could you please add the Rens hub to the list of options?

It actually ranks higher than Hek for activity: https://market.fuzzwork.co.uk/

**Comment by sudorandom** [comment]
Thanks for opening this issue. I'll look into adding it to the list.

**Comment by sudorandom** [comment]
@nagledb I added Rens as a market option. Let me know if it looks good!

**Comment by nagledb** [comment]
Looks great, thank you!
