### ISSUE TITLE
Unknown Format

### ISSUE THREAD

**Issue by jonberling** [evepraisal/go-evepraisal#40]
Appraisal with the format: evepraisal.com/a/dbnxs

The format is AMOUNT whitespace ITEM. There may be leading or trailing whitespace.

The whitespace may be tabs or spaces.

**Comment by sudorandom** [comment]
This is fixed in 66da65bac8b9ae27a1e9d3712a6440bd57ab7091 and e72b440ad42b6e2f916ff578b5084c75063006ab. It'll be released soon. Thanks for the report!
