### ISSUE TITLE
Legacy API URL's return 404

### ISSUE THREAD

**Issue by GunfighterJ** [evepraisal/go-evepraisal#5]
For example, http://evepraisal.com/e/17981203.json returns a 404.

I'm using scripts to parse evepraisal links put into courier contracts, and currently I have to follow a redirect from the non-api endpoint to get the new alphanumeric ID, then get the JSON page from the new URL.

Could a legacy API endpoint be added please? From my understanding the content of the JSON object is the same format with some additions.

**Comment by sudorandom** [comment]
YES! Try now. I had this in before but the functionality broke when I changed how the routing works.

The format is mostly the same with the exception that IDs can be strings (and a couple other small details that hopefully won't matter).

**Comment by GunfighterJ** [comment]
That worked. Thanks!

**Comment by sudorandom** [comment]
@GunfighterJ new appraisal IDs are returned in the "X-Appraisal-ID" header.

**Comment by GunfighterJ** [comment]
Another awesome feature. Thanks!
