### ISSUE TITLE
Integration with Excel?

### ISSUE THREAD

**Issue by zyanazeredin** [evepraisal/go-evepraisal#52]
Thanks very much for the wonderful work with Evepraisal.com - it is an awesome idea!

Now, straight to the point. I would like to set up and use an Excel (Office 365) sheet to automatically look up a group of 68 items (all PI) on evepraisal. And I would like to do it three times, in both Jita, Amarr and Dodixie.

I can set this up, already have, but the problem is the 'persist' format. If I don't use 'persist appraisals' then Evepraisal can't remember the items to search for, and if I do use 'persist' it remembers the items but also the exact search and so it doesn't update the prices...

As far as I can tell, Excel can only understand this format "https://evepraisal.com/a/fcvbm" (for example), when making a web query.

Any suggestions or tips on how to make this work would be greatly appreciated :-)

Final note: I am only making this sheet for myself, not for public dissemination. I have it setup to update the query only when I first open the sheet, which won't be very often. I do understand that every time I do, I will be making 3x 68 requests on Evepraisal, but I am hoping/believing that this is within reason and not something that threatens to overload the service. I will also promise that before, if ever, I share the sheet with anyone, I will ask you first if it is alright!

Best regards,
Zyana Zeredin

**Comment by sudorandom** [comment]
I'm not sure about Excel... It probably has a way of consuming JSON. Almost every page on evepraisal can be represented as a JSON object if you add ".json" to the end. Taking your example: https://evepraisal.com/a/fcvbm.json
