### ISSUE TITLE
Azbel prices, check it pls

### ISSUE THREAD

**Issue by Passvv0rd** [evepraisal/go-evepraisal#54]
https://evepraisal.com/item/35826 Sell 4kkk, buy 4.1kkk, in the game - buy 3.4kkk
ty.

**Comment by sudorandom** [comment]
I need a bit more information. Where in game? Which market tab are you looking at (jita, universe, amarr, etc).

**Comment by Passvv0rd** [comment]
Jita, of course

2018-01-13 4:09 GMT+03:00 Kevin McDonald <notifications@github.com>:
