### ISSUE TITLE
Config always sets to default

### ISSUE THREAD

**Issue by Traace** [evepraisal/go-evepraisal#56]
Hi, it seems like there is no config reading. The application always fall back to its defaults.

The code says:
 `func main() {
	log.SetFlags(log.LstdFlags | log.Lshortfile)

	viper.SetConfigType("toml")
	viper.SetConfigName("evepraisal")
	viper.AddConfigPath("/etc/evepraisal/")
	viper.AddConfigPath(".")
	viper.SetEnvPrefix("evepraisal")
	viper.AutomaticEnv()
	err := viper.ReadInConfig()
	if err != nil {
		switch err.(type) {
		case *os.PathError:
			log.Println("No config file found, using defaults")
		default:
		}
}`

So I just added a basic toml config "evepraisal" under /etc/evepraisal/

`title = "evepraisal"

[evepraisal]
base-url = "http://192.168.0.XX:8080"
http_addr = "192.168.0.XX:8080"
managment_addr = "192.168.0.XX:8090"`

However, evepraisal just ignores that...

Editing the IP in config.go viper.SetDefault and rebuild the whole application is a bit overloaded

**Comment by sudorandom** [comment]
The full path of the config file is `/etc/evepraisal/evepraisal.toml`. Make sure you include the `.toml`

**Comment by Traace** [comment]
Damn me. Yes I forgot the ending .toml . I will try to stop open issues that are none in future.
( Github really needs a way for privat messaging, or did I just miss that feature? )

Thanks for the help, I love evepraisal, just never worked with anything go related
