### ISSUE TITLE
Error in parsing integers

### ISSUE THREAD

**Issue by jeff4747** [evepraisal/go-evepraisal#59]
The parser does not appear to recognize a decimal point.

If you put 100 Ferrogel in the box, the appraisal includes 100 Ferrogel
If you put 100.00 Ferrogel in the box, the appraisal includes 10,000 Ferrogel

Expected behavior would be to truncate at the decimal point.

**Comment by sudorandom** [comment]
Integers don't typically have decimal points... But the behavior is confusing. I've made some adjustments to the parser to handle this better
