### ISSUE TITLE
API - Appraisals with content-type text/plain

### ISSUE THREAD

**Issue by bahrmichael** [evepraisal/go-evepraisal#63]
My appraisal on https://thebuyback.space is based on evepraisal, thanks a lot for that! Currently I'm still "faking" browser calls from the time when the API wasn't around yet.

As our buyback service has rather large contracts to appraise, using the uri for the appraisal won't work (e.g. 8000 characters). I think saving those lists to the disk and then sending that to you is bad practice, too.

So **how about an API to send the appraisal (as in the search form) via text/plain**? Just like the multipart, but with text/plain as the content type.

**Comment by bahrmichael** [comment]
<3

**Comment by sudorandom** [comment]
@bahrmichael Let me know if you see any issues with this!
