### ISSUE TITLE
=EVEPRAISAL_ITEM(17867,"jita","sell") never returns value.

### ISSUE THREAD

**Issue by lucianodonati** [evepraisal/go-evepraisal#71]
=EVEPRAISAL_ITEM(17867,"jita","sell") stays in "Loading" forever.
It only happens with this value for me.

**Comment by sudorandom** [comment]
@lucianodonati is this still happening? It seems to work okay for me now.

**Comment by lucianodonati** [comment]
Fixed it by copying the whole sheet, creating a new one, and pasting there.
Google sheets bug? 
Thank you for your time @sudorandom .

**Comment by sudorandom** [comment]
@lucianodonati yeah, maybe. There is some amount of caching that happens so that might have caused this issue. I see the same thing on your google doc and see that it's fixed when I made a copy of it. Very strange. Definitely let me know if it happens again!
