### ISSUE TITLE
No link generation.

### ISSUE THREAD

**Issue by RedJackkk** [evepraisal/go-evepraisal#73]
I tried to make some priceing but when i click submit the link will be :https://buyback.karmafleet.org/appraisal
i tried to change with the gear icon, refreshed the page several time, but its not working now (used some times before) thanks for the good site, love it!

**Comment by sudorandom** [comment]
Do you have javascript disabled? It relies on javascript to change the link in order to save time on a redirect.

**Comment by RedJackkk** [comment]
It was enabled. i used the site just 5 minute before it bugged. I tried in
internet explorer and worked perfectly fine. Maybe the chrome did something
wrong.

2018-06-02 5:45 GMT+02:00 Kevin McDonald <notifications@github.com>:
