### ISSUE TITLE
Unknown Format

### ISSUE THREAD

**Issue by Jonnyw2k** [evepraisal/go-evepraisal#75]
Appraisal with the format: evepraisal.com/a/i9hwh

Describe the format (where you got it, etc)
Exported loot list from fleet window, seemed to work alright, format is:
TIME<TAB>CHARACTER<TAB>ITEM TYPE<TAB>QTY<TAB>ITEM TYPE

**Comment by sudorandom** [comment]
This is added as a supported format. Thanks for the report!
