### ISSUE TITLE
Blueprint Tab in Industry Window

### ISSUE THREAD

**Issue by shaynefitzgerald** [evepraisal/go-evepraisal#77]
Appraisal with the format: evepraisal.com/a/j175h

Ctrl-A in the blueprint tab, Ctrl-C/Ctrl-V into evepraisal window.

Would be great to quickly catalog what blueprints are available. Currently the heuristic parser interprets ME as quantity.

**Comment by sudorandom** [comment]
Thanks @shaynefitzgerald. I'll look at adding it today!

**Comment by sudorandom** [comment]
@shaynefitzgerald I've added support for this format. Here's an example of the same appraisal with the new parser: http://evepraisal.com/a/j175h
