### ISSUE TITLE
Spreadsheet various projectile Weapons not found

### ISSUE THREAD

**Issue by Pubbles** [evepraisal/go-evepraisal#78]
Hey,
the EVPRAISAL_ITEM() command isn't able to find any 800mm, 425mm, 220mm, 200mm, 150mm and 125mm Autocannons (only polarized versions work). A few Artillery versions are affected too but I didn't checked them all.

The error code is the following:
Exception: Request failed for https://evepraisal.com/item/800mm%20Repeating%20Cannon%20II.json returned code 404. Truncated server response: {"error_title":"Not Found","error_message":"I couldn't find what you're looking for"} (use muteHttpExceptions option to examine full response) (Zeile 77).

I hope it was a mistake on my side but I think I checked everything twice so I think it is a bug.

Awesome tool btw and thank you for it!

Tim

**Comment by sudorandom** [comment]
I've fixed this and deployed the fix. Try it out and let me know how it works!
