### ISSUE TITLE
Spreadsheet Function - "item 12753 not found (line 99)"

### ISSUE THREAD

**Issue by ZipSlings** [evepraisal/go-evepraisal#83]
I double checked that this should be the correct ID for the Impel with a third party. Anyone else having this issue? Or is this known. Thank you in advance!

![image](https://user-images.githubusercontent.com/44013724/46712558-864f1580-cc06-11e8-8f83-b9e98d3ca39c.png)

**Comment by ZipSlings** [comment]
Having the same issue with Badger, Crane, and Tayra

**Comment by sudorandom** [comment]
@ZipSlings yesterday I released a new version of the spreadsheet addon that tried to reduce the total number of API requests by batching. It looks like there's still some kinks to work out there... I reverted the version for now but it's still waiting for google's review process.

I'm sorry for the inconvenience
