### ISSUE TITLE
Compare Different Trade Hubs

### ISSUE THREAD

**Issue by AaronOpfer** [evepraisal/go-evepraisal#87]
I'd like to see what I pasted into the "Quick Estimate" box still be there after I click "Submit" so that I can then perform the estimate again at a different trade hub.

**Comment by sudorandom** [comment]
This sounds good. I will probably make this an option that you can configure instead of making this the default behavior because of the potential to break other people's workflow.

**Comment by AaronOpfer** [comment]
w.r.t breaking workflow, you could make the previous text stay in the text field but have it be pre-highlighted so that a click + Control+V still replaces the text as it does now.

**Comment by sudorandom** [comment]
@AaronOpfer I went ahead and implemented this. Take a look on the live site! https://evepraisal.com

**Comment by AaronOpfer** [comment]
Nice! :+1:
