### ISSUE TITLE
Corp Moon ledger

### ISSUE THREAD

**Issue by HurenOgeko** [evepraisal/go-evepraisal#89]
The following data taken from the corp moon mining ledger cannot be processed in its raw form (names changed to protect the guilty):
```
2019.01.19	Corp name	miner 1	Ytterbite	8,625	86,250 m³	70,377,757 ISK
2019.01.19	Corp name	miner 1	Bountiful Ytterbite	2,940	29,400 m³	38,004,556 ISK
2019.01.19	Corp name	miner 2	Ytterbite	7,667	76,670 m³	62,560,726 ISK
2019.01.19	Corp name	miner 2	Bountiful Ytterbite	612	6,120 m³	7,911,152 ISK
2019.01.19	Corp name	miner 3	Ytterbite	8,741	87,410 m³	71,324,287 ISK
2019.01.19	Corp name	miner 4	Ytterbite	244	2,440 m³	1,990,976 ISK
2019.01.19	Corp name	miner 4	Bountiful Ytterbite	976	9,760 m³	12,616,478 ISK
2019.01.19	Corp name	miner 5	Bountiful Ytterbite	732	7,320 m³	9,462,359 ISK
2019.01.19	Corp name	miner 6	Bountiful Ytterbite	732	7,320 m³	9,462,359 ISK
2019.01.19	Corp name	miner 7	Ytterbite	11,786	117,860 m³	96,170,695 ISK
2019.01.19	Corp name	miner 8	Bountiful Ytterbite	805	8,050 m³	10,406,009 ISK
```

**Comment by HurenOgeko** [comment]
eveprisal response:
Invalid input
No valid lines found

**Comment by HurenOgeko** [comment]
yes I know the isk values are in the ledger copy/paste but I liked to compile it into one list and get actual jita prices...not to mention quickly totaling up the m3

**Comment by HurenOgeko** [comment]
the first post is format if you just ctrl-a then ctrl-c on it. I found if you click the bottom copy to clipboard button you get a bit different output and have a slightly different effect on evepraisal:
Timestamp	Corporation	Pilot	Ore Type	Quantity	Volume	Est. Price	Ore TypeID	SolarSystemID
2019.01.19	Corp Name	miner 1	Ytterbite	8625	86250	70377757	45513	30003687
2019.01.19	Corp Name	miner 1	Bountiful Ytterbite	2940	29400.0	38004556	46318	30003687
2019.01.19	Corp Name	miner 2	Ytterbite	7667	76670	62560726	45513	30003687
2019.01.19	Corp Name	miner 2	Bountiful Ytterbite	612	6120.0	7911152	46318	30003687
2019.01.19	Corp Name	miner 3	Ytterbite	8741	87410	71324287	45513	30003687
2019.01.19	Corp Name	miner 4	Ytterbite	488	4880	3981953	45513	30003687
2019.01.19	Corp Name	miner 4	Bountiful Ytterbite	976	9760.0	12616478	46318	30003687
2019.01.19	Corp Name	miner 5	Ytterbite	244	2440	1990976	45513	30003687
2019.01.19	Corp Name	miner 5	Bountiful Ytterbite	732	7320.0	9462359	46318	30003687
2019.01.19	Corp Name	miner 6	Ytterbite	244	2440	1990976	45513	30003687
2019.01.19	Corp Name	miner 6	Bountiful Ytterbite	732	7320.0	9462359	46318	30003687
2019.01.19	Corp Name	miner 7	Ytterbite	11786	117860	96170695	45513	30003687
2019.01.19	Corp Name	miner 8	Ytterbite	244	2440	1990976	45513	30003687
2019.01.19	Corp Name	miner 8	Bountiful Ytterbite	805	8050.0	10406009	46318	30003687

**Comment by sudorandom** [comment]
Thanks for the detailed report! I added support for both formats: copy/paste and the 'copy to clipboard' button. Let me know how it works for you!
