### ISSUE TITLE
Varying number of decimal places used leads to difficulty in reading at a glance

### ISSUE THREAD

**Issue by pedter** [evepraisal/go-evepraisal#9]
In all three value columns (Single, Total, and ISK/m3), varying number of decimal places are used (ex: http://evepraisal.com/a/bxfhu). As a result, numbers within each column no longer line up for ease of reading. Using the standard two decimals places everywhere (even if with a check-box that users can opt in to use) would make reading values at a glance easier.

**Comment by sudorandom** [comment]
I'm thinking of only showing the 2 decimal places (for everything) if there is an item with a low enough value to show low decimal places. But until then, I'll quickly change it to always show 2 decimal places for ISK values.

**Comment by sudorandom** [comment]
This has been fixed (in c12aa99) and deployed. The live site now shows two decimal positions for ISK. Thanks for the feedback!

**Comment by pedter** [comment]
That looks excellent; much appreciated!
