### ISSUE TITLE
New station for google doc

### ISSUE THREAD

**Issue by nsbarsbars** [evepraisal/go-evepraisal#93]
Hi Folks,

Is is possible to set not one of the most popular hub, but set something different (station in Low or NPC space for instance) in Google Doc function ? 

=EVEPRAISAL_ITEM(A6;"hek")   instead "hek" name of station or ID for instnase

**Comment by sudorandom** [comment]
@nsbarsbars afraid not. Evepraisal only computes the prices for major trade hubs. A lot would have to change to get prices everywhere and that kind of thing is out of scope for this tool. I feel like tooling from evemarketer.com would make more sense for this
