### ISSUE TITLE
Unknown Format

### ISSUE THREAD

**Issue by PeterMustermann** [evepraisal/go-evepraisal#96]
Appraisal with the format: evepraisal.com/a/md222

remove leading white spaces : string.replace(/^\s*//") or s/^ *//g or trim(line)

393 Compressed Stable Veldspar
185 Compressed Glossy Scordite
 105 Compressed Brilliant Gneiss
  23 Compressed Jet Ochre
  13 Compressed Pellucid Crokite

**Comment by sudorandom** [comment]
This is fixed
